### ISSUE TITLE
Error in density.default

### ISSUE THREAD

**Issue by JHereward** [tbenavi1/smudgeplot#21] opened 2018-10-30 03:03 UTC
Hi there,

Just trying this out using the KMC instructions - looks like a great program. I'm getting the following error when running smudgeplot.R:

running	Smudgeplot v0.1.3

######################
######################
Error in density.default(.total_pair_cov[.subset], adjust = .adjust) : 
  need at least 2 points to select a bandwidth automatically
Calls: estimate_1n_coverage_1d_subsets -> get_1d_peaks -> density -> density.default
Execution halted

Any Idea why?

**Comment by KamilSJaron** [comment] 2018-10-30 09:33
Hi @JHereward, thanks for trying out smudgeplots. 

I would guess that the `_coverages_2.tsv` file is empty, but it's hard to say without any other info. Would you mind giving me some more info:
- number of lines of the `_coverages_2.tsv` file
- if the histogram looks sane? (if you would post the kmer histogram here, it would be even better)
- L and R values you have chosen for the coverage thresholds
- perhaps the commands you have used

If you don't want to share your data publicly, would you mind sharing them via email?

**Comment by JHereward** [comment] 2018-11-04 23:44
Hi there, thanks heaps for making it - looks really great!

The _coverages_2.tsv file seems OK, two columns of numbers like this:

261	493
275	354
309	377
211	263
200	444
270	399
248	347

I've attached the histograms and they don't look good, this is Miseq paired end 300 data from short read archive SRR2032117 - I guess maybe the lack of a good kmer peak is causing trouble? I tried to clean up the data and error correct it - but still get the same error message.

I couldn't even get genomescope to run on the .hist originally, but if you run jellyfish without the -C option it seems to work. I don't fully understand what the -C option of jellyfish does, but removing it did seem to help. I tried with KMC as well, but the results were the same.

![genomescope using -c in jellyfish](https://user-images.githubusercontent.com/28075757/47971632-23ef1500-e0df-11e8-9a39-eb06d8ee014e.JPG)
![genomescope without -c in jellyfish](https://user-images.githubusercontent.com/28075757/47971635-26516f00-e0df-11e8-9b9f-86e0a9d57d61.JPG)

**Comment by KamilSJaron** [comment] 2018-11-05 00:45
Hmm, this is not very nice kmer spectra. Somehow you can not really see the genome. This kind of kmer spetra one see when
- there is too much PCR during library prep
- there is too much contamination
- it's really old sequencing run (Illumina 10 years ago was quite messy)
Especially first two are very common problems for species with low input DNA (like nematodes).

The reason why this is a problem is that if the variance of converage is too high, we are not able to separate peaks that relate to copy number in the genome.

Anyway, none of this is actually answer why smudgeplot does not work. I am pulling the data now, I will check it tomorrow. 

Thanks again for trying smudgeplots.

**Comment by JHereward** [comment] 2018-11-05 02:30
Hi, yes it was WGA from a single nematode egg, and 600 cycle Miseq, which never really worked well, maybe I can find a better dataset for this species.

Here are the tsv and kmer hist files, happy to send anything else along if it helps?



[Reniform.zip](https://github.com/tbenavi1/smudgeplot/files/2546701/Reniform.zip)

**Comment by tbenavi1** [comment] 2018-11-05 03:51
Yes, this kmer spectrum does not have clearly defined peaks. I took a look at the SRA run selector for Rotylenchulus reniformis and found the following datasets:

WGA:
SRR2032116
SRR2032115
SRR2027991

WGS:
SRR2029859
SRR2029858
SRR2029861
SRR2029860
SRR949277
SRR949271
SRR2027999

I was able to download the datasets and use KMC to create histograms combining the data from the datasets (see attached). Unfortunately, even pooling across all these samples, the resulting kmer spectra do not have clearly defined peaks, and GenomeScope is unable to converge. I'm not sure what can be done other than getting higher quality sequencing. 
[WGA.hist.txt](https://github.com/tbenavi1/smudgeplot/files/2546862/WGA.hist.txt)
[WGS.hist.txt](https://github.com/tbenavi1/smudgeplot/files/2546863/WGS.hist.txt)

**Comment by KamilSJaron** [comment] 2018-11-06 15:01
Hi @JHereward , Hi Rhyker :)

I think why you get the error. The naive script I wrote for guessing L is searching for the local minima and the local minima of your kmer spectra is more than 200x although I suspect that the genome coverage is ~20x. So if you chosen L using the script, it filtered out basically all the genomic kmers and the kernel smoothing indeed failed because of 0 points with ratio 0.48 - 0.5, which is used for the first draft of genomic coverage estimate. I have to add some safety break in there. Thank you for this.

Now about our species, when I used smaller L, I got super messy smudgeplot as well. This is what happens with PCR, I am sorry. The evidence is very very weak, but in the all the mess smudgeplot guesses it to triploid. Is that possible? 

![rren1_smudgeplot](https://user-images.githubusercontent.com/8181573/48072228-516db880-e1dc-11e8-80ce-c961816c6f58.png)

Maybe I could try to run it on the samples @tbenavi1 found.

**Comment by KamilSJaron** [comment] 2018-11-06 17:13
That's strange. I can not reproduce the error. Could you share me somehow the `kmer_pairs_coverages_2.tsv` file?

**Comment by JHereward** [comment] 2018-11-06 23:07
Hi there, here it is:

[Reniform.zip](https://github.com/tbenavi1/smudgeplot/files/2555346/Reniform.zip)


I got 200 and 600 for the Lower and Upper estimates.

Triploid is interesting, we don't really have any idea about this one. We have been looking at this because people tend to use ribosomal genes for phylogenetics in this group - but there are at least two copies - so species get split across different clades. We were looking to design a new marker and wanted to try to understand the reason behind the duplications. Genomescope correctly identified the genome as 195mb, but indicated only 50mb unique sequence. 

Perhaps there has been an ancient duplication of a large part of the genome?

**Comment by KamilSJaron** [comment] 2018-11-07 16:48
Thanks a lot. I realized where the bug is.

L = 200, U = 600 means that the coverage ration of kmer pairs could be 200 / 600 at least. And one of the smudge identification techniques is subseting stripes of kmer ratio coverages for peaks around 1/2, 1/3, 1/4 and 1/5. The subset in 1/5 category was empty therefore the kernel smoothing function have thrown an exception.

Long story short. This problem will fixed in the next commit.

However, got to say that the genome coverage is definitely way way bellow 200x and even if you update your smudgeplot and rerun the analysis, you won't get a meaningful result. Genoscope guesses the genome coverage to 26x, smudgeplot with more sane filtering to 21x. I guess that the genome assembly is quite bad, no?

I gave a brief look at the two other sequencing project linked and by my rough calculations the coverages are approx 25x and 36x. That's bit better, but I am afraid not sufficient if wga was used (which I suppose since the peaks are blended). Both genomescope and smudgeplot are very sensitive to coverage and even more to coverage variance and therefore I am afraid that i must agree with Rhyker - you need better sequencing data for a proper genome characterization.

**Comment by KamilSJaron** [comment] 2018-11-07 16:50
Resolved in 4abe43fe969b327726159391b2662797487474fe

**Closed by KamilSJaron** 2018-11-07 16:50 UTC
Labels: bug, genomescope_included, smudgeplot_included
